import turtle
m=turtle.Turtle()
m.speed(0)
m.penup()
def sq(l1,l2):
    for i in range(2):
        m.pensize(5)
        m.pencolor("black")
        m.fd(l1)
        m.lt(90)
        m.fd(l2)
        m.lt(90)
def emoji():
     m.begin_fill()
     m.circle(200)
     m.color("gold")
     m.end_fill()
     m.goto(100,240)
     m.color("black")
     m.down()
     m.begin_fill()
     m.circle(25)
     m.end_fill()
     m.up()
     m.goto(-100,240)
     m.down()
     m.begin_fill()
     m.circle(25)
     m.end_fill()
     m.up()
     m.pensize(10)
     m.color("black")
     m.goto(-70,80)
     m.down()
     sq(145,30)
     m.begin_fill()
     m.color("white")
     sq(23,15)
     m.up()
     m.goto(-50, 80)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(-30, 80)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(-10, 80)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(10, 80)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(30, 80)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(50, 80)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(50, 95)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(30, 95)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(10, 95)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(-10, 95)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(-30, 95)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(-50, 95)
     m.down()
     sq(23, 15)
     m.up()
     m.goto(-70, 95)
     m.down()
     sq(23, 15)
     m.end_fill()

emoji()


m.hideturtle()
turtle.done()
