import turtle
def go(t,x,y):
    t.penup()
    t.goto(x,y)
    t.pendown()
def polygon(t,n,length):
     for i in range(n):
         t.fd(length)
         angle=360/n
         t.rt(angle)
def rectangle(t,length1,length2):
    t.fd(length1)
    t.rt(90)
    t.fd(length2)
    t.rt(90)
    t.fd(length1)
    t.rt(90)
    t.fd(length2)
    t.rt(90)
mytturtle=turtle.Turtle()
#mytturtle.speed(500)
mytturtle.begin_fill()
mytturtle.color('black')
polygon(mytturtle,4,320)
mytturtle.end_fill()
go(mytturtle,20,-20)
mytturtle.begin_fill()
mytturtle.color('blue')
polygon(mytturtle,4,280)
mytturtle.end_fill()
go(mytturtle,40,-30)
mytturtle.begin_fill()
mytturtle.color('black')
rectangle(mytturtle,32,16)
mytturtle.end_fill()
go(mytturtle,90,-30)
mytturtle.begin_fill()
mytturtle.color('black')
rectangle(mytturtle,32,16)
mytturtle.end_fill()
go(mytturtle,150,-20)
mytturtle.begin_fill()
mytturtle.color('black')
rectangle(mytturtle,16,32)
mytturtle.end_fill()
go(mytturtle,190,-30)
mytturtle.begin_fill()
mytturtle.color('black')
rectangle(mytturtle,32,16)
mytturtle.end_fill()
go(mytturtle,240,-30)
mytturtle.begin_fill()
mytturtle.color('black')
rectangle(mytturtle,32,16)
mytturtle.end_fill()
turtle.done()